name = "Tribes That May Be"
author = "Jonathan Freedman"
version = "2.2.1-alpha.1+cb5c5e9a.542326503.319"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aa49da94bf92afcbefc93ebed8ab5c9695335b7ce1e00d5fb1546ef6fa5b1ec"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
