#!/usr/bin/env bash
set -e
SCRIPTDIR=$( cd "${0%/*}" && pwd)
ROOTDIR="${SCRIPTDIR%/*}"

usage() {
    echo "${0} <container_version> <artifact_version>"
    exit 1
}

problems() {
    echo "Error: ${*}"
    exit 1
}

if [ $# != 2 ] ; then
    usage
fi

CONTAINER_VERSION="$1"
VERSION="$2"
shift 2

DOCKER_IMAGE="ghcr.io/tribedsthatmaybe/workflow:${CONTAINER_VERSION}"
ARTIFACT_PATH="${ROOTDIR}/artifacts"
ARTIFACT="${ARTIFACT_PATH}/ttmb-server-${VERSION}.zip"
if [ ! -e "$ARTIFACT" ] ; then
    problems "${ARTIFACT} does not exist (bad version?)"
fi

if ! docker inspect "$DOCKER_IMAGE" &> /dev/null ; then
    make -C "$ROOTDIR" container_build
fi
docker run \
       --rm \
       -v "${ROOTDIR}:/mnt" \
       "$DOCKER_IMAGE" \
       devsync "$VERSION"
