#!/usr/bin/env bash
set -e
SCRIPTDIR=$( cd "${0%/*}" && pwd)
ROOTDIR="${SCRIPTDIR%/*}"
DOCKER_IMAGE="tribesthatmaybe/modpack:honk"

usage() {
    echo "${0} <version>"
    exit 1
}

problems() {
    echo "Error: ${*}"
    exit 1
}

if [ $# != 1 ] ; then
    usage
fi

VERSION="$1"
shift

ARTIFACT_PATH="${ROOTDIR}/artifacts"
ARTIFACT="${ARTIFACT_PATH}/ttmb-server-${VERSION}.zip"
if [ ! -e "$ARTIFACT" ] ; then
    problems "${ARTIFACT} does not exist (bad version?)"
fi

if ! docker inspect "$DOCKER_IMAGE" &> /dev/null ; then
    make -C "$ROOTDIR" container_build
fi
docker run \
       --rm \
       -v "${ROOTDIR}:/mnt" \
       "tribesthatmaybe/modpack:honk" \
       devsync "$VERSION"
