#!/usr/bin/env bash
set -e
SCRIPTDIR=$( cd "${0%/*}" && pwd)
ROOTDIR="${SCRIPTDIR%/*}"

usage() {
    echo "${0} <container_version> <artifact_version>"
    exit 1
}

problems() {
    echo "Error: ${*}"
    exit 1
}

if [ $# != 2 ] ; then
    usage
fi

CONTAINER_VERSION="$1"
VERSION="$2"
shift

DOCKER_IMAGE="ghcr.io/tribesthatmaybe/workflow:${CONTAINER_VERSION}"
RELEASE="release"
RELEASE_FILE="${ROOTDIR}/release"
if [ -e "$RELEASE_FILE" ] ; then
    RELEASE="$(cat "$RELEASE_FILE")"
fi

if ! docker inspect "$DOCKER_IMAGE" &> /dev/null ; then
    make -C "$ROOTDIR" container_build
fi

docker run \
       --rm \
       -v "${ROOTDIR}:/mnt" \
       "ghcr.io/tribedsthatmaybe/workflow:${CONTAINER_VERSION}" \
       upload "$VERSION" "$RELEASE"
